# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Renhou' do
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Renhou

  

  platform :ios, '9.0'
  target 'RenhouTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Renhou-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Renhou-tvOS

  target 'Renhou-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
